Update botssh

diff --git a/Modulos/botssh b/Modulos/botssh
--- a/Modulos/botssh
+++ b/Modulos/botssh
@@ -1,9 +1,9 @@
 #!/bin/bash
 #====================================================
-#	SCRIPT: BOT WEBCONT
-#	DESARROLLADO POR:	NET_SATOSHI
-#	CONTACTO TELEGRAM:	http://t.me/Net_Satoshi
-#	CANAL TELEGRAM:	http://t.me/WEBCONT_OFC
+#	SCRIPT: BOTSSH SSHPLUS MANAGER
+#	DESENVOLVIDO POR:	CRAZY_VPN
+#	CONTATO TELEGRAM:	http://t.me/crazy_vpn
+#	CANAL TELEGRAM:	http://t.me/sshplus
 #====================================================
 clear
 [[ $(awk -F" " '{print $2}' /usr/lib/licence) != "@Net_Satoshi" ]] && exit 0
@@ -67,7 +67,7 @@ fun_botOnOff() {
             cd $HOME
         }
         fun_bar 'fun_bot1'
-        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT WEBCONT ACTIVADO !\033[0m" || echo -e "\n\033[1;31m ERROR! REANALISE SUS INFORMACIONES\033[0m"
+        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT WEBCONT ACTIVADO !\033[0m" || echo -e "\n\033[1;31m ERROR! REVISE SU INFORMACION\033[0m"
         sleep 2
         menu
     } || {
@@ -91,10 +91,10 @@ fun_botOnOff() {
 
 fun_instbot() {
     echo -e "\E[44;1;37m             INSTALADOR BOT WEBCONT                \E[0m\n"
-    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCION\033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCION \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
     echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mACCEDE AL SIGUIENTE BOT DESDE TU TELEGRAM\033[1;37m:\033[0m"
     echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREE SU BOT \033[1;31mOPCION: \033[1;37m/newbot\033[0m"
-    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@WEBCONT_BOT \033[1;33mE PEGUE SU ID \033[1;31mOPCION: \033[1;37m/id\033[0m"
+    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@WEBCONT \033[1;33mY PEGUE SU ID \033[1;31mOPCION: \033[1;37m/id\033[0m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
     echo ""
     read -p "DESEA CONTINUAR ? [s/n]: " -e -i s resposta
